create or replace view KSFPA.ONLINE_UGAM_PVT.CANCELLED_ORDERS_CC_HD_ORDER_COUNT(
	ORDER_DATE,
	CC_COUNT,
	HD_COUNT,
	TOTAL_ORDER_COUNT
) as
SELECT TO_DATE(DO_PACKING) AS Order_Date
      ,COUNT(DISTINCT(CASE WHEN CUSTOMERORDERTYPE = 'CAC' THEN so.EXTERNALORDERID END)) AS CC_Count
      ,COUNT(DISTINCT(CASE WHEN CUSTOMERORDERTYPE = 'STD' THEN so.EXTERNALORDERID END)) AS HD_Count
      ,COUNT(DISTINCT so.EXTERNALORDERID) AS Total_Order_Count
FROM "KSFPA"."OMS"."CUSTOMERORDER" co
JOIN "KSFPA"."OMS"."STOREORDER" so
ON co.ORDERID = so.ORDERID
WHERE so.DO_PACKING > '2020-06-29 00:00:00'
      AND so.DO_PACKING < CONCAT(CURRENT_DATE()-1, ' 23:59:59')
//  and co.CustomerOrderType = 'CAC'
GROUP BY 1
ORDER BY 1 ASC;