create or replace view KSFPA.ONLINE_UGAM_PVT.OMS_STORE_DASHBOARD_TRADE(
	FY_PW,
	STORE_ID,
	UNITS
) as
SELECT FY_PW, Store_ID, SUM(UNITS) as Units
FROM KSFPA.ONLINE_UGAM_PVT.WKLY_DIF_TBP
WHERE ORDER_TYPE = 'All'
GROUP BY FY_PW, Store_ID;