create or replace view KSFPA.ONLINE_UGAM_PVT.ONE_PASS_RECOGNIZED_SALES(
	FY_PW,
	YEAR,
	PERIOD,
	WEEK,
	SALES
) as

SELECT FY_PW,
Year,
PERIOD,
WEEK,
--SUM(TOTAL_SELLING_PRICE_WITHOUT_GST) AS Sales_M,
SUM(CASE WHEN FINAL_SUBSCRIPTION_STATUS IN ('Active','Trial','Active-Converted') THEN TOTAL_SELLING_PRICE_WITHOUT_GST ELSE 0 END) as Sales
FROM
(
SELECT
    --CONCAT(ACCOUNTING_YEAR,'||',ACCOUNTING_WEEK_NUMBER) as FY_WN,
    CONCAT ('FY', ACCOUNTING_YEAR,
            'P', 
             RIGHT (ACCOUNTING_PERIOD_DESCRIPTION,2),
             'W',
             ACCOUNTING_WEEK_NUMBER
                 ) AS FY_PW,
    d.ACCOUNTING_YEAR as Year,
    d.ACCOUNTING_PERIOD_DESCRIPTION as Period,
    d.ACCOUNTING_WEEK_NUMBER as WEEK,
    DD_EXTERNALORDERID as TXN,
    FINAL_SUBSCRIPTION_STATUS,
    DATE,
    TOTAL_SELLING_PRICE_WITHOUT_GST, //not including GST
    //QUANTITY_SOLD,
    DD_ONEPASSUUID AS TOTAL_OP
FROM 
    KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.SALES.FACT_SALES_DETAIL fsd
LEFT JOIN 
    KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.COMMON_DIMENSIONS.DIM_DATE d
    ON d.SK_DATE_ID = fsd.FK_DATE_ID
LEFT JOIN 
    KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.ADVANTAGE.ONEPASS_SUBSCRIPTION_HISTORY_VW SH
    ON SH.ONEPASS_ID = FSD.DD_ONEPASSUUID
    AND SH.FINAL_DIM_DATE = DATE(FSD.Transaction_Timestamp)
WHERE 
    FSD.FK_SOURCE_SYSTEM_ID = 15 //filtering for online (including refunds)
    AND ACCOUNTING_YEAR >= 2022
    --DATE(DATE) BETWEEN '2023-07-22' AND '2023-07-31' //set date range here
    --AND FINAL_SUBSCRIPTION_STATUS IN ('Active','Trial','Active-Converted') //only including sales for active/subscribed members
    AND FINAL_SUBSCRIPTION_STATUS IS NOT NULL
)
GROUP BY    
    1, YEAR, PERIOD, WEEK
ORDER BY 
    1;